version: '3.8'

services:
  imagegen-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Add your environment variables here
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - FAL_KEY=${FAL_KEY}
      # - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - imagegen-network

networks:
  imagegen-network:
    driver: bridge 